### ISSUE TITLE
global.getBlobForArrayBuffer is not a function

### ISSUE THREAD

**Issue by ionflow** [mrousavy/react-native-blob-jsi-helper#13]
Does this error mean I'm not adding this library properly? I'm trying to use binary data (PNG image) sent through a websocket in an Image component in react native. 
```
Error converting ArrayBuffer to Blob: [TypeError: global.getBlobForArrayBuffer is not a function (it is undefined)]
```

These are the steps I followed to install:

1. `npx expo install react-native-blob-jsi-helper`
2. `eas build --profile development --platform ios` to run a fresh build
3. Installed new build on my iOS device
4. Then ran `npx expo start --dev-client` locally
5. Error happens during this code:
```
try {
  const blob = getBlobForArrayBuffer(event.data);
  const url = URL.createObjectURL(blob);
  setMessages((prevMessages) => [...prevMessages, url]);
} catch (error) {
  console.error("Error converting ArrayBuffer to Blob:", error);
}
```

**Comment by mrousavy** [comment]
Maybe the JSI installer func did not get installed? Could you try setting a breakpoint on the native side

**Comment by ionflow** [comment]
I forgot to run `npx pod-install`. Now that error is gone.

As a side note, I don't think I'm using this correctly. Should this work?
```
const blob = getBlobForArrayBuffer(event.data);
const url = URL.createObjectURL(blob);
setMessages((prevMessages) => [...prevMessages, url]);
...
{messages.map((message, index) => {
  <Image
    key={`image-${index}`}
    source={{ uri: message}}
    style={{ width: 200, height: 200, resizeMode: "contain" }}
  />
})}
```

Currently it's just rendering a white box, but no errors.

**Comment by mrousavy** [comment]
I don't know what `event` is, sorry.

**Comment by ionflow** [comment]
It's just a websocket `MessageEvent`. In my case `event.data` is an `ArrayBuffer`.
